export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_NEW_CATEGORY_REQUEST: " ADD_NEW_CATEGORY_REQUEST",
    ADD_NEW_CATEGORY_SUCCESS: " ADD_NEW_CATEGORY_SUCCESS",
    ADD_NEW_CATEGORY_FAILURE: " ADD_NEW_CATEGORY_FAILURE",
};

export const productConstants = {
    GET_PRODUCTS_BY_SLUG: "GET_PRODUCTS_BY_SLUG",
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

    GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
    GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
    GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",
};

export const initialDataConstants = {
    GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
    GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
    GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const authConstants = {
    USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
    USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
    USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
    USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
};

export const cartConstants = {
    FETCH_CART_REQUEST: "FETCH_CART_REQUEST",
    FETCH_CART_SUCCESS: "FETCH_CART_SUCCESS",
    FETCH_CART_FAILURE: "FETCH_CART_FAILURE",

    ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

    UPDATE_CART_REQUEST: "UPDATE_CART_REQUEST",
    UPDATE_CART_SUCCESS: "UPDATE_CART_SUCCESS",
    UPDATE_CART_FAILURE: "UPDATE_CART_FAILURE",

    CLEAR_FROM_CART_REQUEST: "CLEAR_FROM_CART_REQUEST",
    CLEAR_FROM_CART_SUCCESS: "CLEAR_FROM_CART_SUCCESS",
    CLEAR_FROM_CART_FAILURE: "CLEAR_FROM_CART_FAILURE",
};

export const orderConstants = {
    ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
    ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
    ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",

    CANCEL_ORDER_REQUEST: "CANCEL_ORDER_REQUEST",
    CANCEL_ORDER_SUCCESS: "CANCEL_ORDER_SUCCESS",
    CANCEL_ORDER_FAILURE: "CANCEL_ORDER_FAILURE",
};
